<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../ninjascript/BreakBoxTypes.cs" Condition="Exists('../ninjascript/BreakBoxTypes.cs')" />
    <Compile Include="../ninjascript/BreakBoxCloud.cs" Condition="Exists('../ninjascript/BreakBoxCloud.cs')" />
    <Compile Include="../ninjascript/BreakBoxCore.cs" Condition="Exists('../ninjascript/BreakBoxCore.cs')" />
    <Compile Include="../ninjascript/BreakBoxExits.cs" Condition="Exists('../ninjascript/BreakBoxExits.cs')" />
    <Compile Include="../ninjascript/BreakBoxHistory.cs" Condition="Exists('../ninjascript/BreakBoxHistory.cs')" />
    <Compile Include="../ninjascript/AveragingEngineCore.cs" Condition="Exists('../ninjascript/AveragingEngineCore.cs')" />
  </ItemGroup>
</Project>
